virtual_coupling.k_pos_x: 1000.0
virtual_coupling.k_pos_y: 1000.0
virtual_coupling.k_pos_z: 600.0

virtual_coupling.d_pos_x: 50.0
virtual_coupling.d_pos_y: -1.0
virtual_coupling.d_pos_z: -1.0

virtual_coupling.k_rot_x: 50.0
virtual_coupling.k_rot_y: 500.0
virtual_coupling.k_rot_z: 50.0
  
virtual_coupling.d_rot_x: -1.0
virtual_coupling.d_rot_y: 20.0
virtual_coupling.d_rot_z: -1.0  

nullspace.damping: 0.0

tool.length: -0.06 # length of the tool attached to the flange, in meters

log.enabled: true
log.timing: true
log.robot_state: false  #  ee position, velocity, joint states, ...
log.haptic_input: false  # target pose
log.virtual_coupling: false  # interface variables and forces
log.controller_parameters: true  # Gains