arm_id: fr3
joints:
  - fr3_joint1
  - fr3_joint2
  - fr3_joint3
  - fr3_joint4
  - fr3_joint5
  - fr3_joint6
  - fr3_joint7

pd_gains.kp: [500.0, 600.0, 500.0, 600.0, 200.0, 275.0, 50.0]
# pd_gains.kd: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
pd_gains.kd: [-1.0, -1.0, -1.0, -1.0, -1.0, 25.0, -1.0] # Use negative values for automatic damping calculation


ik.tolerance: 0.01 # Position tolerance for IK convergence
ik.max_iterations: 1000 # Maximum number of IK iterations
# ik.damping_factor: 0.000001 # Damping factor for IK solver (Levenberg-Marquardt)

filter.joint_targets: 0.05 # Amount of smoothing for joint targets using EMA (0=no smoothing, 1=no filtering)

log.enabled: true
log.robot_state: true
log.target_pose: true
log.control_torques: true
log.control_gains: true
log.ik_convergence: true
log.timing: true