arm_id: fr3
joints:
  - fr3_joint1
  - fr3_joint2
  - fr3_joint3
  - fr3_joint4
  - fr3_joint5
  - fr3_joint6
  - fr3_joint7

task:
  k_pos_x: 500.0
  k_pos_y: 500.0
  k_pos_z: 500.0

  d_pos_x: 50.0
  d_pos_y: 50.0
  d_pos_z: 50.0

  k_rot_x: 100.0
  k_rot_y: 100.0
  k_rot_z: 100.0
  
  d_rot_x: 5.0
  d_rot_y: 5.0
  d_rot_z: 5.0

log:
  enabled: true
  timing: true
  robot_state: false
  controller_parameters: false
  control_values: false
  control_actions: false
  dynamic_params: false
  limits: false