# Request (empty)
---
# Response
uint8 CONTROL_MODE_PAUSE = 0
uint8 CONTROL_MODE_CART_POSE = 1
uint8 CONTROL_MODE_CART_VEL = 2
uint8 CONTROL_MODE_JOINT_POSE = 3
uint8 CONTROL_MODE_JOINT_VEL = 4
uint8 control_mode