# Request
float64[] ee_velocity  # [vx, vy, vz, wx, wy, wz] in [m/s, rad/s]
builtin_interfaces/Duration duration  # [sec]  
---
# Result
bool success
string error
---
# Feedback
float64[] ee_velocity  # [rad/s]