default:
  experiments:
  - franka_rim_data_20250911_145004
  output_filename: processed_data.pkl
  topics:
    fr3_joint_states: /fr3/joint_states
    fr3_pose: /fr3/current_pose
    haptic_pose: /haptic_pose
    rim_force: /rim/interface_force
    rim_pose: /rim/pose
