gains.k_pos_x: 1000.0
gains.k_pos_y: 1000.0
gains.k_pos_z: 5000.0

gains.d_pos_x: -1.0
gains.d_pos_y: -1.0
gains.d_pos_z: -1.0

gains.k_rot_x: 80.0
gains.k_rot_y: 80.0
gains.k_rot_z: 80.0
  
gains.d_rot_x: 1.0
gains.d_rot_y: 1.0
gains.d_rot_z: 1.0

log.enabled: true
log.timing: true
log.robot_state: true
log.haptic_input: false
log.virtual_coupling: false
log.controller_parameters: true